# Generated by Django 4.2.4 on 2023-08-15 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0005_alter_cart_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
